variables:
  REMOTE_HOST: deploy@172.16.5.193
  API_IMAGE: ${CI_REGISTRY_IMAGE}/api
  WEBAPP_IMAGE: ${CI_REGISTRY_IMAGE}/webapp


stages:          # List of stages for jobs, and their order of execution
  - test
  - build
  - deploy

test:
  image: node:latest
  stage: test
  script:
    # Go to api directory
    - cd api
    # Run npm commands
    - npm install && npm test
    # Go to webapp directory
    - cd ../webapp
    # Run npm commands
    - npm install && npm test

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
    # Go to webapp directory
    - cd ../webapp
    # Run npm commands
    - npm run build
    # Build Webapp
    - docker build -f webapp/DockerfileServer -t "${WEBAPP_IMAGE}" .


deploy:
  image: alpine:latest
  stage: deploy
  script:
    # push Webapp
    - docker push "${WEBAPP_IMAGE}"
    - apk update && apk add rsync openssh curl
    # Prepare SSH settings
    - mkdir -p ~/.ssh && (umask  077 ; echo "${DEPLOY_KEY_PRIVATE}" | base64 -d > ~/.ssh/id_rsa)
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    # Prepare files for transfer
    - mkdir remote_dir
    - cp docker-compose.server.yml remote_dir/docker-compose.yml
    - echo "API_IMAGE=${API_IMAGE}" >> remote_dir/.env
    - echo "WEBAPP_IMAGE=${WEBAPP_IMAGE}" >> remote_dir/.env
    # Transfer to server
    - rsync -r remote_dir "${REMOTE_HOST}:./"
    # Run commands on the server
    - ssh ${REMOTE_HOST} /bin/bash 
            "
            echo 'Starting..';
            cd ~/remote_dir;
            docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY;
            docker-compose pull;
            docker-compose up -d;
            "
