services:
  backend:
    build:
      context: ./backend
    ports:
      - '3000:3000'
    volumes:
      - './backend:/opt/app'
    environment:
      - "CI:'true'"
    restart: always
  frontend:
    build:
      context: ./frontend
    ports:
      - '5001:5001'
    volumes:
      - './frontend:/opt/app'
    restart: always
